# Chapter 1: NumPy 基礎

教材：ゼロから作る Deep Learning  
目的：NumPy配列と行列計算に慣れ、ニューラルネット計算の土台を理解する

### 環境確認

In [22]:
import sys
import numpy as np
import pandas as pd

print("python:", sys.version.split()[0])
print("numpy:", np.__version__)
print("pandas:", pd.__version__)

python: 3.11.9
numpy: 2.4.1
pandas: 3.0.0


### NumPy 配列の基本
配列の形（shape）と型（dtype）を確認  
shape：配列の“サイズ情報”  
dtype：要素の型


In [23]:
x = np.array([1.0, 2.0, 3.0])
print("x:", x)
print("shape:", x.shape)
print("dtype:", x.dtype)

x: [1. 2. 3.]
shape: (3,)
dtype: float64


### 行列（2次元配列）

shape = (行数, 列数) 

In [24]:
A = np.array([[1, 2], [3, 4]])
print(A)
print("shape:", A.shape)

[[1 2]
 [3 4]]
shape: (2, 2)


### 要素ごとの演算

In [25]:
B = np.array([[10, 20], [30, 40]])
print("A + B:\n", A + B)
print("A * B:\n", A * B)

A + B:
 [[11 22]
 [33 44]]
A * B:
 [[ 10  40]
 [ 90 160]]


### 行列積

@ は 行列積（行列の掛け算）  
C は単位行列なので、A @ C = A

In [26]:
C = np.array([[1, 0], [0, 1]])
print("A @ C:\n", A @ C)

A @ C:
 [[1 2]
 [3 4]]


### ブロードキャスト

A は (2,2)、v は (2,)であるが、ブロードキャストを用いて拡張  
バイアス加算で使われることが多い

In [27]:
v = np.array([10, 20])
print("A + v:\n", A + v)

A + v:
 [[11 22]
 [13 24]]


## まとめ
- NumPy配列は数式のかたまり
- shape を意識するのが大事
- 行列積（@）がNNの基本計算
- ブロードキャストは暗黙的に形を合わせてくれる